appi_4.0/edge_system/edge_system/info_machine/views.py
from operator import mod
from flask import Blueprint, render_template, request, flash, jsonify, abort
import json
from flask.helpers import url_for
import numpy as np
from datetime import date, datetime, timedelta
from flask_login import login_required
from sqlalchemy.sql.elements import and_
from werkzeug.utils import redirect
import requests
from sqlalchemy import or_, and_

from edge_system import db, remote_server, max_num_records_to_upload
from edge_system.info_machine.model.machine import Machine, RegisterForm
from edge_system.info_machine.model.part_info import Part, UploadPartsHist
from edge_system.info_machine.model.rework_part_info import ReworkPart, UploadReworkPartsHist

def get_remote_informatio():
    """
    Getting the remote information to register the new machine 
    """
    data = {}

    ### getting lines ... 
    url_lines = remote_server + 'Lineas/linea/cargar/'
    try:
        response = requests.post(url_lines)
    except:
        flash('Error: not server connection','danger')
        return data 
    #print("\t JSON data: \n", response.json())
    data_lines = response.json()
    if data_lines: # por ahora no hay una opción cuando regrese vació #'' in response.json():
        data['lines'] = []
        for line in data_lines:
            info_line = ('{}'.format(line['id']), line['name'])
            data['lines'].append(info_line)
            #print(line)
        print(data['lines'])
    ### getting suppliers .. Falta este endpoint .. 
    data['suppliers'] = []
    data['suppliers'].append(('1', 'ASBajio'))
    ### getting 
    return data  

def get_id_remote_machine(nickname_machine): # no esta como unico en la base de datos pero lo manejaremos por ahora así, hasta que regrese el id el endpoint de guardado
    url_machine = remote_server + 'Maquinas/maquina/cargar'
    id = -1
    try:
        response = requests.post(url_machine)
    except:
        flash('Error: Ca not get remote machine id!!! ','danger')
        return id
    data_machines = response.json()
    if data_machines:
        #print('looking for ..... ', nickname_machine)
        for machine_ in data_machines:
            #print(machine_)
            if nickname_machine == machine_['nickname']:
                return machine_['id']
    return id 

def save_remote_info_cachine(machine_info):
    url_machine_save = remote_server + 'Maquinas/maquina/guardar'
    payload = {
        'nickname': machine_info['nickname'],
        'description': machine_info['description'],
        'brand': machine_info['brand'],
        'model': machine_info['model'],
        'voltage': machine_info['voltage'],
        'amperage': machine_info['amperage'],
        'serie': machine_info['serie'],
        'id_line': machine_info['id_line'],
        'manufacturing_date': machine_info['manufacturing_date'],
        'instalation_date': machine_info['instalation_date'],
        'id_supplier': machine_info['id_supplier'],
        'run_date': machine_info['run_date'],
    }
    try:
        response = requests.post(url_machine_save, data=payload)
        flash('Saved in remote server')
    except:
        flash('Error: not server connection','danger')
        return -1 
    id = get_id_remote_machine(machine_info['nickname']) 
    #print('::: ID ', id)
    return id   

def get_machine_info_json():
    try:
        with open("edge_system/static/tmp/machine.json", "r") as read_file:
            data = json.load(read_file)
    except:
        print("ERROR")
        return None
    return data

machine = Blueprint('machine', __name__)

@machine.before_request  # con esto, esta función se ejecuta antes de cada endpoint que tengamos definido en este documento
@login_required
def constructor():
   pass

@machine.route('/machine/register_json')
def fill_machine_register_json():
    data_json = get_machine_info_json()
    form = RegisterForm(meta={'csrf': False})
    form.id.data = 13
    form.path_image.data = 'img/tmp_workstation_01.jpeg'
    form.nickname.data = data_json['nickname']
    form.description.data = data_json['description']
    form.brand.data = data_json['brand']
    form.model.data = data_json['model']
    form.voltage.data = int(data_json['voltage'])
    form.amperage.data = float(data_json['amperage'])
    form.serie.data = data_json['serie']
    form.id_line.data = int(data_json['id_line'])
    form.manufacturing_date.data = datetime.strptime(data_json['manufacturing_date'], '%Y-%m-%dT%H:%M:%S')
    form.instalation_date.data = datetime.strptime(data_json['instalation_date'], '%Y-%m-%dT%H:%M:%S')
    form.id_supplier.data = int(data_json['id_supplier'])
    form.run_date.data = datetime.strptime(data_json['run_date'], '%Y-%m-%dT%H:%M:%S')
    
    return render_template('machine/register.html', form = form)
    #return redirect(url_for('machine.machine_register', form = form))


@machine.route('/machine/register', methods=['GET', 'POST'])
def machine_register():
    print("HOLAAAA")
    if Machine.query.first():
        flash("Machine information already registered!!")
        return redirect(url_for('machine.info'))
    data = get_remote_informatio()
    form = RegisterForm(meta={'csrf': False})
    form.id_supplier.choices = [('0', 'unknown')]
    form.id_line.choices = [('0', 'unknown')]
    if data:
        form.id_supplier.choices = data['suppliers']
        form.id_line.choices = data['lines']
    if form.validate_on_submit():
        #if Machine.query.get(form.id.data):
        #    flash('Machine already registered!')
        #    return redirect(url_for('machine.machine_register'))
        machine_info = {
            'nickname': form.nickname.data,
            'description': form.description.data,
            'brand': form.brand.data,
            'model': form.model.data,
            'voltage': form.voltage.data,
            'amperage': form.amperage.data,
            'serie': form.serie.data,
            'id_line': int(form.id_line.data),
            'manufacturing_date': form.manufacturing_date.data,
            'instalation_date': form.instalation_date.data,
            'id_supplier': int(form.id_supplier.data),
            'run_date': form.run_date.data,
        }
        path_image = 'img/tmp_workstation_01.jpeg' #form.path_image.data
        print(machine_info)
        id_remote_machine = save_remote_info_cachine(machine_info)
        if id_remote_machine  == -1:
            return redirect(url_for('home.home_page')) 
        machine_ =  Machine(id=id_remote_machine,
        nickname=machine_info['nickname'],
        description=machine_info['description'],
        brand=machine_info['brand'],
        model=machine_info['model'],
        voltage=machine_info['voltage'],
        amperage=machine_info['amperage'],
        serie=machine_info['serie'],
        id_line=machine_info['id_line'],
        manufacturing_date=machine_info['manufacturing_date'],
        instalation_date=machine_info['instalation_date'],
        id_supplier=machine_info['id_supplier'],
        run_date=machine_info['run_date'],
        path_image= path_image)
        print(machine_)
        db.session.add(machine_)
        db.session.commit()
        flash("Machine information saved locally!!")
        return redirect(url_for('home.home_page'))
    if form.errors:
        flash(form.errors, 'danger')
    return render_template('machine/register.html', form = form)

@machine.route('/machine/info')
def info():
    machine_ = Machine.query.first()
    if not machine_:
        flash("Machine information has not been registered!!", 'danger')
        return redirect(url_for('machine.machine_register'))
    print(machine_)
    return render_template("machine/machine_info.html", machine = machine_)

@machine.route('/upload')
def upload_historical():
    return render_template("machine/upload_records.html")


def from_model_to_data_parts(parts):
    data_records = []
    idx_min_max = []
    if not parts:
        return data_records
    idxs = []
    for part in parts:
        idxs.append(part.id)
        data_records.append({
            "timestamp":part.timestamp.strftime("%Y-%m-%dT%H:%M:%S"),
            "status": "True" if part.status else "False",
            "working_time":"{}".format(part.working_time)
        })
    idx_min_max = [min(idxs), max(idxs)]
    print('----------------- ',idx_min_max)
    return data_records, idx_min_max

def upload_parts_record(data_to_upload):
    url_upload_parts = remote_server + 'Maquinas/maquina/lmi_parts'
    print('url ::::: ', url_upload_parts)
    #print(data_to_upload)
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    #headers = {
    #    "Cache-Control": "no-cache",
	#    "Postman-Token": "2fe1650d-a961-2c45-27b8-3f8b7d4a217c",
	#    "Content-Type": "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW"
    #}
    #response = requests.post(url_upload_parts, headers=headers, data=data_json)
    #response = requests.post(url_upload_parts, data=data_json)
    payload = {'datos': json.dumps(data_to_upload)}
    response = requests.post(url_upload_parts, data=payload, headers=headers)
    #print("\t Response: ", response)
    print (response.text)
    #print("\t Response headers: ", response.headers)
    if( "aviso" in response.text):
        if("Datos almacenados con" in response.text):
            print("------------------------ Datos almacenados!!!")
            return True
    return False

def get_min_max_idx(idx_min_max, idx_min_max_subset):
    print('::::::::::: min_max = {} \t ::::::::: subset_min_max = {}'.format(idx_min_max, idx_min_max_subset))
    if not idx_min_max:
        idx_min_max = [idx_min_max_subset[0], idx_min_max_subset[1]]
    else:
        idx_min_max =[
            min(idx_min_max[0], idx_min_max_subset[0]),
            max(idx_min_max[1], idx_min_max_subset[1])
        ]
    return  idx_min_max

def save_in_db_upload_record_parts(idx_min_max, offset_):
    upload_parts_hist = UploadPartsHist(

appi_4.0/edge_system/edge_system/templates/fragment/_alert.html
{% with messages = get_flashed_messages() %}
{% if messages %}

    {% for message in messages %}
    <div class="alert alert-success fade show mt-3">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

{% endif %}
{% endwith %}

appi_4.0/edge_system/edge_system/templates/fragment/_footer.html
  
<footer class="bg-light text-center text-dark text-lg-start">
    <div class="text-center p-3" style="background-color: hsla(225, 6%, 13%, 0.2);">
      © 2021 Copyright:
      <a class="text-dark" href="http://www.asbajio.mx" target="_blank">ASBajío</a>
    </div>
</footer>

appi_4.0/edge_system/edge_system/templates/fragment/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="http://www.asbajio.mx"  target="_blank"> 
        <span><img src="{{ url_for('static',filename='img/asb-logo_01.png')}}" height="50"/></span> 
        &emsp; Historical Data Visualization</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
      </ul>
      <ul class="navbar-nav ">
          {% if not current_user.username %}
        <li class="nav-item"></li>
          <a class="nav-link" href="{{ url_for('fauth.login') }}">Login </a>
        </li>
        {% endif %}
        {% if current_user.username %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('machine.info') }}">Info Machine</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('machine.upload_historical') }}">Upload Records</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('machine.production_information', static_period = 'Day', type_info = 'OK-NOK')}}">Metrics</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                  Hola: {{ current_user.fullname }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Perfil </a>
                  <a class="dropdown-item" href="{{ url_for('fauth.logout') }}">Logout </a>
                </div>
              </li>
            {% endif %}
      </ul>
    </div>
  </nav>

appi_4.0/edge_system/edge_system/templates/fragment/_sidebar_end.html
    </div>
</div>


<script>
    window.addEventListener('DOMContentLoaded', event => {

// Toggle the side navigation
const sidebarToggle = document.body.querySelector('#sidebarToggle');
if (sidebarToggle) {
    // Uncomment Below to persist sidebar toggle between refreshes
    // if (localStorage.getItem('sb|sidebar-toggle') === 'true') {
    //     document.body.classList.toggle('sb-sidenav-toggled');
    // }
    sidebarToggle.addEventListener('click', event => {
        console.log("ENTRO")
        event.preventDefault();
        document.body.classList.toggle('sb-sidenav-toggled');
        localStorage.setItem('sb|sidebar-toggle', document.body.classList.contains('sb-sidenav-toggled'));
    });
}

});
</script>

appi_4.0/edge_system/edge_system/templates/fragment/_sidebar_start.html
<div class="d-flex" id="wrapper">
    <!-- Sidebar-->
    <div class="border-end bg-white" id="sidebar-wrapper">
      <div class="sidebar-heading border-bottom bg-light">Production Metrics</div>
      <div class="list-group list-group-flush dropdown">
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#">Periods</a>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle p-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              OK and NOK data
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Day', type_info = 'OK-NOK')}}">Day</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Week', type_info = 'OK-NOK')}}">Week</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Month', type_info = 'OK-NOK')}}">Month</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle p-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Production time data
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Day', type_info = 'Working-Time')}}">Day</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Week', type_info = 'Working-Time')}}">Week</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Month', type_info = 'Working-Time')}}">Month</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle p-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Rework parts
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Day', type_info = 'Rework')}}">Day</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Week', type_info = 'Rework')}}">Week</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Month', type_info = 'Rework')}}">Month</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle p-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Reworking time data
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Day', type_info = 'Reworking-Time')}}">Day</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Week', type_info = 'Reworking-Time')}}">Week</a>
              <a class="dropdown-item" href="{{ url_for('machine.production_information', static_period = 'Month', type_info = 'Reworking-Time')}}">Month</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle p-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Downtime for maintenance
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#!">Day</a>
              <a class="dropdown-item" href="#!">Week</a>
              <a class="dropdown-item" href="#!">Month</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle p-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Downtime for outservice
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#!">Day</a>
              <a class="dropdown-item" href="#!">Week</a>
              <a class="dropdown-item" href="#!">Month</a>
            </div>
          </li>
        </ul>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!"></a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/">Home</a>
        <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{{ url_for('machine.info') }}">Machine Info</a>    
      </div>
    </div>
    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
      <button class="btn btn-primary" id="sidebarToggle">Metrics Menu</button>
        
        <!-- Page content-->